# Generated by Django 4.2.5 on 2023-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lesson_product_user_remove_products_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is the product', max_length=255),
            preserve_default=False,
        ),
    ]
