# Generated by Django 4.2.5 on 2023-09-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_delete_productpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
